sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

haxe:
 # - "3.2.1"
  - "3.4.7"
 # - development

env:
 # - HAXE_TARGET=cpp
 # - HAXE_TARGET=cs
 # - HAXE_TARGET=flash
 # - HAXE_TARGET=lua
 # - HAXE_TARGET=neko
 # - HAXE_TARGET=node
  - HAXE_TARGET=php
  - HAXE_TARGET=php7
 # - HAXE_TARGET=python
 #- HAXE_TARGET=js
 # - HAXE_TARGET=java

matrix:
  fast_finish: true
  allow_failures:
    - haxe: development
    - env: HAXE_TARGET=flash  # see https://github.com/travis-ci/travis-ci/issues/8481
    - haxe: "3.2.1"
      env: HAXE_TARGET=cpp
    - os: osx
  exclude:
    - haxe: "3.2.1"
      env: HAXE_TARGET=lua
    - haxe: "3.2.1"
      env: HAXE_TARGET=php7
    - haxe: development
      os: osx

install:
  #- haxelib git tink_io https://github.com/haxetink/tink_io pure
  #- haxelib git tink_cli https://github.com/haxetink/tink_cli pure
  - haxelib install tink_io
  - haxelib install tink_cli
  - haxelib git travix https://github.com/sebthom/travix && pushd . && cd $(haxelib config)travix/git && git checkout python_fix && haxe build-neko.hxml && popd
  - haxelib run travix install
  - haxelib dev haxe-doctest .
  #- haxelib install travix
  - haxelib install hx3compat
  - haxelib install munit
  - haxelib install tink_testrunner

script:
  - haxelib run travix $HAXE_TARGET
